### ISSUE TITLE
[Question] Training and Testing

### ISSUE THREAD

**Issue by DhruvalkumarShah** [amine0110/Liver-Segmentation-Using-Monai-and-PyTorch#1]
Hello, @amine0110. I'm a beginner in AI. How did you separated testing and training dataset from the dataset you referred in your Youtube tutorial. If you could explain which files you entered in testing and training part would be great. Thanks in advance

**Comment by amine0110** [comment]
Hi @DhruvalkumarShah ,

I did a random choice when I chose the train/test data and I did that manually since I did not have a lot of patients.

You can use 75% train and 25% test
