### ISSUE TITLE
AddChannel removed

### ISSUE THREAD

**Issue by arojproj** [amine0110/Liver-Segmentation-Using-Monai-and-PyTorch#11]
Thank you for the complete ML segmentation code. Compiling the preprocess.py gave me:

ImportError: cannot import name 'AddChanneld' from 'monai.transforms'. 

It seems AddChannel has been removed in recent Monai. How to adjust the code you provided for the removed AddChannel?

**Comment by amine0110** [comment]
Hi,

Yes, I think this module has been removed from the library, there is a module called EnsureFirstChannel that was being used instead, you can check this example, they used it here: https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/spleen_segmentation_3d_visualization_basic.ipynb

**Comment by arojproj** [comment]
You were right, changing it to EnsureFirstChannel solved the problem. Many thanks.

**Comment by amine0110** [comment]
My pleasure 😄
