### ISSUE TITLE
import error in preprocess

### ISSUE THREAD

**Issue by anuragp2018** [amine0110/Liver-Segmentation-Using-Monai-and-PyTorch#12]
ImportError: cannot import name 'AddChannel' from 'monai.transforms.

**Comment by mohammedvelmeni** [comment]
Hi,

Yes, this function has been removed by MONAI, you can replace it be this: https://docs.monai.io/en/stable/transforms.html#ensurechannelfirst

**Comment by amine0110** [comment]
Hi,

Yes, this function has been removed by MONAI, you can replace it by this: https://docs.monai.io/en/stable/transforms.html#ensurechannelfirst
