### ISSUE TITLE
UNet error

### ISSUE THREAD

**Issue by anuragp2018** [amine0110/Liver-Segmentation-Using-Monai-and-PyTorch#13]
Traceback (most recent call last):
  File "d:\liver_seg_github\Liver-Segmentation-Using-Monai-and-PyTorch\train.py", line 15, in <module>
    model = UNet(
            ^^^^^
TypeError: UNet.__init__() got an unexpected keyword argument 'dimensions'

**Comment by amine0110** [comment]
Hi

This keyword has been changed to spatial_dims:

<img width="382" alt="image" src="https://github.com/amine0110/Liver-Segmentation-Using-Monai-and-PyTorch/assets/37108394/39c20140-d5e9-4579-bcab-bfce6c506236">
