### ISSUE TITLE
test_outputs = test_outputs > 0.53

### ISSUE THREAD

**Issue by BK0x7C8** [amine0110/Liver-Segmentation-Using-Monai-and-PyTorch#6]
hey dude,

thanks for your awesome tutorials.

I use some of your code and everything works great. However, the only thing I did not understand, is using  `test_outputs = test_outputs > 0.53` in your testing.ipynb. I know, why you use it, to just plot the elements inside the array of predictions above a threshold, but why 0.53, and not, say, 0.5?

Cheers!

**Comment by amine0110** [comment]
Hi there,

Actually, it was chosen after some tests on the dataset, there is no specific reason for that value haha

**Comment by BK0x7C8** [comment]
Ok, I set mine to 0.5 and it looks alright :) Thanks for the clarification.
