### ISSUE TITLE
repeat bug in group creation

### ISSUE THREAD

**Issue by xiaochenhehub** [amine0110/Liver-Segmentation-Using-Monai-and-PyTorch#9]
Hi amine, 
I am afraid the create_groups function in preprocess.py has a bug. 
It just start from the same slice index when it create a sub-folder. 
It might be fixed like this, 

```
num_slices = 65
for patient in glob(input_path+"/*"):
    patient_name = os.path.basename(patient)
    slice_list = sorted(glob(patient+"/*"))
    num_folders = int(len(slice_list)/num_slices)
    for i in range(num_folders):
        output_path_name = os.path.join(output_path, patient_name + f"_{i}")
        os.mkdir(output_path_name)
        for file in slice_list[num_slices*i:num_slices*(i+1)]:
            shutil.copy(file, output_path_name)
```

**Comment by amine0110** [comment]
Hi 

In the function I am using, I am doing `shutil.move(file, output_path)` and not `shutil.copy(file, output_path)`. This means we can't find the same file in the second loop!

**Comment by xiaochenhehub** [comment]
Thanks for the reply. I have realized where I went wrong. 😅
